all:
	cd adc; make
	cd Can; make
	cd dac; make
	cd flexray; make
	cd gpio; make
	cd pwm; make
	cd test; make
	cd volmoni; make
	cd AUTOSAR_FlexRay; make
	cd multi_thread; make

clean:
	cd adc; make clean
	cd Can; make clean
	cd dac; make clean
	cd flexray; make clean
	cd gpio; make clean
	cd pwm; make clean
	cd test; make clean
	cd volmoni; make clean
	cd AUTOSAR_FlexRay; make clean
	cd multi_thread; make clean

