

all:
	cd adcapi; make
	cd canapi; make
	cd dacapi; make
	cd flexrayapi; make
	cd gpioapi; make
	cd powaccapi; make
	cd pwmapi; make
	cd testapi; make

clean:
	cd adcapi; make clean
	cd canapi; make clean
	cd dacapi; make clean
	cd flexrayapi; make clean
	cd gpioapi; make clean
	cd powaccapi; make clean
	cd pwmapi; make clean
	cd testapi; make clean

